version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    # labels:
    #   - "central-pipeline"
    commit-message:
      prefix: "chore" # Indicates a feature for new Major versions
    allow:
      - dependency-type: "direct"
