version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "sleighsoft/test"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    commit-message:
      prefix: "chore" # Indicates a feature for new Major versions
    allow:
      - dependency-type: "direct"
