name: Multi-Trigger Workflow

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  run-multi-trigger-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display trigger info
        run: |
          echo "This workflow was triggered by ${{ github.event_name }}"
          if [ "${{ inputs.someInput }}" ]; then
            echo "Input provided: ${{ inputs.someInput }}"
          fi

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          # Add additional languages like python, cpp, etc., if needed.

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
