name: Reusable Echo Workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "hello"
  print-workflow-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow Name
        run: echo "Workflow file name: $GITHUB_WORKFLOW"
