name: test-condition
on:
  workflow_dispatch:
    inputs:
      tfapply:
        type: boolean
        description: If true, "apply" terraform changes. Otherwise, run "plan"
        default: false
        required: true
      
permissions:
  contents: read
jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: flag_true
        id: flag_true
        run: echo "flag_true=true" >> $GITHUB_OUTPUT
      - name: true-out
        if: ${{ fromJSON(steps.flag_true.outputs.flag_true) }}
        run: echo "Flag was true"

      - name: flag_false
        id: flag_false
        run: echo "flag_false=false" >> $GITHUB_OUTPUT
      - name: false-out
        if: ${{ fromJSON(steps.flag_false.outputs.flag_false) }}
        run: echo "Flag was true, expected skip!"
      
      - name: flag_false_contains
        id: flag_false_contains
        run: |
          echo "flag_false_contains=${{ contains(fromJSON('["testt", "hello"]'), 'test')}}" >> $GITHUB_OUTPUT
          echo $flag_false_contains
      - name: false-out-contains
        if: ${{ fromJSON(steps.flag_false_contains.outputs.flag_false_contains) }}
        run: echo "Flag was true, expected skip!"
      
      - name: flag_true_contains
        id: flag_true_contains
        run: |
          echo "flag_true_contains=${{ contains(fromJSON('["test", "hello"]'), 'test')}}" >> $GITHUB_OUTPUT
          echo $flag_true_contains
      - name: true-out-contains
        if: ${{ fromJSON(steps.flag_true_contains.outputs.flag_true_contains) }}
        run: echo "Flag was true"
      
      - name: flag_true_contains_and
        id: flag_true_contains_and
        run: |
          echo "flag_true_contains_and=${{ contains(fromJSON('["test", "hello"]'), 'test') && contains(fromJSON('["test", "hello"]'), 'hello') }}" >> $GITHUB_OUTPUT
          echo $flag_true_contains_and
      - name: true-out-contains
        if: ${{ fromJSON(steps.flag_true_contains_and.outputs.flag_true_contains_and) }}
        run: echo "Flag was true"
      
      
      - name: flag_false_contains_and
        id: flag_false_contains_and
        run: |
          echo "flag_false_contains_and=${{ contains(fromJSON('["test", "hello"]'), 'test') && contains(fromJSON('["test", "hello"]'), 'notin') }}" >> $GITHUB_OUTPUT
          echo $flag_false_contains_and
      - name: true-out-contains
        if: ${{ fromJSON(steps.flag_false_contains_and.outputs.flag_false_contains_and) }}
        run: echo "Flag was true"
      