name: "test-bool-input"
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: JSON
        default: '{"id":"canaryf5","name":"canary","hash":"f5","enabled":false,"regions":{"us1":{"location":"centralus","stages":{"dev":{"data":{"resource_configuration":{"datmssqlserver":{"sku":"50"}}}},"test":{"data":{"resource_configuration":{"datmssqlserver":{"sku":"50"}}}},"uat":{"data":{"resource_configuration":{"datmssqlserver":{"sku":"50"}}}},"prod":{"data":{"resource_configuration":{"datmssqlserver":{"sku":"50"}}}},"connector":{"qc":{"type":"stonemont","name":"mock"},"dispatch":{"type":"command-alkon","name":"mock"},"batch":{"type":"command-alkon","name":"mock"}}}},"us2":{"location":"centralus","stages":{"dev":{"data":{"resource_configuration":{"datmssqlserver":{"sku":"50"}}}},"connector":{"qc":{"type":"stonemont","name":"mock"},"dispatch":{"type":"command-alkon","name":"mock"},"batch":{"type":"command-alkon","name":"mock"}}}},"eu1":{}}}'
        required: true
      
permissions:
  contents: read
jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: write
        run: |
          echo $(cat example-customer.json) >> output.json