name: test-condition
on:
  workflow_dispatch:
    inputs:
      tfapply:
        type: boolean
        description: If true, "apply" terraform changes. Otherwise, run "plan"
        default: false
        required: true
      
permissions:
  contents: read
jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: flag_true
        id: flag_true
        run: echo "flag_true=true" >> $GITHUB_OUTPUT
      - name: true-out
        if: ${{ steps.flag_true.outputs.flag_true }}
        run: echo "Flag was true"
      - name: flag_false
        id: flag_false
        run: echo "flag_false=false" >> $GITHUB_OUTPUT
      - name: false-out
        if: ${{ steps.flag_false.outputs.flag_false }}
        run: echo "Flag was true"