# TODO julian: review code
name: "test-input-json"
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: JSON
        default: '{"id":"canaryf5","regions":{"us1":{}}}'
        required: true
      
permissions:
  contents: read
jobs:
  json:
    runs-on: ubuntu-latest
    outputs:
      customer_id: ${{ steps.customerid.outputs.customer_id }}
      regions: ${{ steps.regions.outputs.regions }}
    steps:
      - name: customerid
        run: |
          customer_id=$(echo '${{ inputs.json }}' | jq ".id" -r)
          echo "$customer_id"
          echo "customer_id=$customer_id" >> $GITHUB_OUTPUT
      - name: regions
        run: |
          regions=$(echo '${{ inputs.json }}' | jq ".regions | keys" -c)
          echo "$regions"
          echo "regions=$regions" >> $GITHUB_OUTPUT
  test-output:
    needs: json
    runs-on: ubuntu-latest
    steps:
      - name: regions
        run: |
          echo ${{ needs.json.outputs.customer_id }}
          echo ${{ needs.json.outputs.regions }}
  create-customer:
    needs: json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson(needs.json.outputs.regions) }}
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo
        run: |
          echo "${{ needs.json.outputs.customer_id }}"
          echo "${{ matrix.region }}"
