name: "test-bool-input"
on:
  workflow_dispatch:
    inputs:
      tfapply:
        type: boolean
        description: If true, "apply" terraform changes. Otherwise, run "plan"
        default: false
        required: true
      
permissions:
  contents: read
jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: lifecycle
        run: |
          [[ ${{ inputs.tfapply }} = "true"  ]] && lifecycle="apply" || lifecycle="plan"
          echo $lifecycle 