# TODO julian: review code
name: "test-input-json"
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: JSON
        default: "{}"
        required: true
      
permissions:
  contents: read
jobs:
  create-customer:
    runs-on: ubuntu-latest
    steps:
      - name: release-checkout
        uses: actions/checkout@v3
      - name: echo
        run: |
          echo "${{ inputs.json }}"
