name: "test-concurrency"
on:
  workflow_dispatch:
    inputs:
      tfapply:
        type: boolean
        description: If true, "apply" terraform changes. Otherwise, run "plan"
        default: false
        required: true
      
permissions:
  contents: read
concurrency: sleep
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 30