# TODO julian: review code
name: "test-input-json"
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: JSON
        default: '{"id":"canaryf5","regions":{"us1":{}}}'
        required: true
      
permissions:
  contents: read
jobs:
  parse-json:
    runs-on: ubuntu-latest
    outputs:
      customer_id: ${{ steps.parse-customerid.outputs.customer_id }}
      regions: ${{ steps.parse-regions.outputs.regions }}
    steps:
      - name: parse-customerid
        run: |
          customer_id=$(echo ${{ inputs.json }} | jq ".id")
          echo $customer_id
      # - name: parse-customerid
      #   run: |
      #     customer_id=$(echo ${{ inputs.json }} | jq ".id")
      #     echo "$customer_id"
      #     echo "customer_id=$customer_id" >> $GITHUB_OUTPUT
      # - name: parse-regions
      #   run: |
      #     regions=$(echo "${{ inputs.json }}" | jq ".regions | keys")
      #     echo "$regions"
      #     echo "regions=$regions" >> $GITHUB_OUTPUT
  create-customer:
    needs: parse-json
    runs-on: ubuntu-latest
    strategy:
      matrix:
        customer_id: ${{ needs.parse-json.outputs.customer_id }}
        region: ${{ needs.parse-json.outputs.regions }}
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo
        run: |
          echo "${{ matrix.customer_id }}"
          echo "${{ matrix.region }}"
