name: "workflow-test"
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        default: '["us1", "us2", "eu1"]'
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        default: '["dev", "test", "uat", "prod"]'
        type: string
jobs:
  deploy:
    uses: ./.github/workflows/workflow-region-template.yml
    with:
      regions: ${{ inputs.regions }}
      stages: ${{ inputs.stages }}
