name: "template: workflow-region"
on:
  workflow_call:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        type: string
jobs:
  deploy-region:
    uses: ./.github/workflows/workflow-stage-template.yml
    strategy:
      matrix:
        region: ${{ fromJSON(inputs.regions) }}
      fail-fast: false
    with:
      region: ${{ matrix.region }}
      stages: ${{ inputs.stages }}
