name: "template: workflow-stage"
on:
  workflow_call:
    inputs:
      region:
        description: "Region"
        required: true
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        type: string
jobs:
  envtest1:
    name: "envtest1"
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST1_SECRET }}"
          echo ${{ secrets.TEST1_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          VAL: ${{ secrets.TEST1_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("VAL")):
            print(q)
  envtest2:
    needs: envtest1
    name: "envtest2"
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST2_SECRET }}"
          echo ${{ secrets.TEST2_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          VAL: ${{ secrets.TEST2_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("VAL")):
            print(q)
  deploy-stage:
    needs: envtest2
    name: "deploy-stage-${{ inputs.region }}-${{ matrix.stage }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: ${{ fromJSON(inputs.stages) }}
      fail-fast: false
    steps:
      - name: echo
        run: echo "${{ inputs.region }} - ${{ matrix.stage }}"
