name: "workflow-test"
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        default: '["us1", "us2", "eu1"]'
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        default: '["dev", "test", "uat", "prod"]'
        type: string
jobs:
  envtest1:
    name: "envtest1"
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST1_SECRET }}"
          echo "${{ secrets.TEST1_SECRET }}" | awk '{print length}'
  envtest2:
    name: "envtest2"
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST2_SECRET }}"
          echo "${{ secrets.TEST2_SECRET }}" | awk '{print length}'
  deploy:
    uses: ./.github/workflows/workflow-region-template.yml
    with:
      regions: ${{ inputs.regions }}
      stages: ${{ inputs.stages }}
    secrets: inherit
