name: "template: workflow-region"
on:
  workflow_call:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        type: string
jobs:
  envtest1:
    name: "envtest1"
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: echo
        run: echo "${{ secrets.TEST1_SECRET }}"
  envtest2:
    name: "envtest2"
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: echo
        run: echo "${{ secrets.TEST2_SECRET }}"
  deploy-region:
    uses: ./.github/workflows/workflow-stage-template.yml
    strategy:
      matrix:
        region: ${{ fromJSON(inputs.regions) }}
      fail-fast: false
    with:
      region: ${{ matrix.region }}
      stages: ${{ inputs.stages }}
