name: "workflow-test"
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        default: '["us1"]'
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        default: '["dev"]'
        type: string
jobs:
  envtest1:
    name: "envtest1"
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST1_SECRET }}"
          echo ${{ secrets.TEST1_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          SECRET: ${{ secrets.TEST1_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("SECRET")):
            print(q)
  envtest2:
    name: "envtest2"
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST2_SECRET }}"
          echo ${{ secrets.TEST2_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          SECRET: ${{ secrets.TEST2_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("SECRET")):
            print(q)
  deploy:
    uses: ./.github/workflows/workflow-region-template.yml
    with:
      regions: ${{ inputs.regions }}
      stages: ${{ inputs.stages }}
    secrets: inherit
