name: "template: workflow-region"
on:
  workflow_call:
    inputs:
      regions:
        description: "List of: ['regionId1', 'regionId2', ...]"
        required: true
        type: string
      stages:
        description: "List of: ['stage1', 'stage2', ...]"
        required: true
        type: string
jobs:
  envtest1:
    name: "envtest1"
    runs-on: ubuntu-latest
    environment: test1
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST1_SECRET }}"
          echo ${{ secrets.TEST1_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          SECRET: ${{ secrets.TEST1_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("SECRET")):
            print(q)
  envtest2:
    name: "envtest2"
    runs-on: ubuntu-latest
    environment: test2
    steps:
      - name: echo
        run: |
          echo "${{ secrets.TEST2_SECRET }}"
          echo ${{ secrets.TEST2_SECRET }} | sed 's/./& /g'
      - name: secret
        env:
          SECRET: ${{ secrets.TEST2_SECRET }}
        shell: python
        run: |
          import os
          for q in (os.getenv("SECRET")):
            print(q)
  deploy-region:
    uses: ./.github/workflows/workflow-stage-template.yml
    strategy:
      matrix:
        region: ${{ fromJSON(inputs.regions) }}
      fail-fast: false
    with:
      region: ${{ matrix.region }}
      stages: ${{ inputs.stages }}
